language: perl
sudo: false
perl:
  - 5.14
  - 5.16
  - 5.18
  - 5.20
  - 5.22
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build && cover -test -report coveralls
